### ISSUE TITLE
请问CL签名中的双线性映射如何实现？

### ISSUE THREAD

**Issue by WystanW** [SecureCats/AIP_BackEnd#8]
您好，读了一下您的代码，好像没有找到CL签名的双线性映射的相关部分，请问这部分的代码如何实现的呢？

**Comment by felinae98** [comment]
您好，非常感谢有人能读我的辣鸡代码，本项目的理论基础建立于C-L在2002年发表的A Signature Scheme with Efficient Protocols中，而双线性的映射的版本提出于2005年发表的Signature Schemes and Anonymous Credentials from Bilinear Maps。如果您是因为毕业设计要研究这方面的东西，请和我多多交流，因为我的毕设方向也与此有关

**Comment by WystanW** [comment]
> 您好，非常感谢有人能读我的辣鸡代码，本项目的理论基础建立于C-L在2002年发表的A Signature Scheme with Efficient Protocols中，而双线性的映射的版本提出于2005年发表的Signature Schemes and Anonymous Credentials from Bilinear Maps。如果您是因为毕业设计要研究这方面的东西，请和我多多交流，因为我的毕设方向也与此有关

您好，我的毕业设计确实用到了这篇论文相关的内容，利用这篇文章做关于广告防作弊的一些东西，请问可以添加您的微信吗？我的微信是Wystan_Wei,邮箱是189546689@qq.com
